-- server/mysql/init.sql
CREATE DATABASE IF NOT EXISTS rezom_2
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'TESTUSER'@'%' IDENTIFIED BY 'rezomsv0811';
GRANT ALL PRIVILEGES ON rezom_2.* TO 'TESTUSER'@'%';
FLUSH PRIVILEGES;
